services:
  - type: web
    name: draw-and-guess
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        value: https://draw-and-guess-1pmz.onrender.com/
      - key: MONGODB_URI
        sync: false
